# Generated by Django 4.2.11 on 2024-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pet_name', models.CharField(max_length=100)),
                ('current_pet_status', models.CharField(max_length=100)),
                ('current_application_status', models.CharField(max_length=100)),
                ('adopter_first_name', models.CharField(max_length=100)),
                ('adopter_last_name', models.CharField(max_length=100)),
                ('adopter_address', models.CharField(max_length=100)),
                ('adopter_email', models.EmailField(blank=True, default='heyyou@example.com', max_length=254)),
            ],
        ),
    ]
