# Generated by Django 4.2.11 on 2024-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam_walk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='current_pet_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='current_pet_status',
            field=models.CharField(max_length=200),
        ),
    ]
