# Generated by Django 4.2.11 on 2024-03-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam_walk', '0002_alter_adopter_current_pet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='adopter_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='adopter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='adopter_first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='adopter_last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='current_application_status',
            field=models.CharField(max_length=200),
        ),
    ]
