# Generated by Django 4.2.6 on 2024-01-29 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('cell_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, default='heyyou@example.com', max_length=254)),
                ('home_phone', models.CharField(blank=True, max_length=15)),
                ('date_entered', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('animals_preference', models.CharField(blank=True, max_length=100)),
                ('disclaimer_signed', models.BooleanField(blank=True, default=False)),
                ('active', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
