# Generated by Django 4.2.9 on 2024-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='active',
            field=models.BooleanField(blank=True, default=False, max_length=2048),
        ),
    ]
