# Generated by Django 4.2.9 on 2024-02-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_alter_volunteers_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='status_notes',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
