# Generated by Django 4.2.9 on 2024-03-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voluntee_role', models.CharField(blank=True, max_length=100)),
                ('volunteers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteers')),
            ],
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
