# Generated by Django 4.2.9 on 2024-03-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_volunteerroles_delete_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerroles',
            old_name='voluntee_role',
            new_name='volunteer_role',
        ),
    ]
