# Generated by Django 4.2.9 on 2024-03-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_rename_voluntee_role_volunteerroles_volunteer_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
        migrations.RenameModel(
            old_name='VolunteerRoles',
            new_name='VolunteerRole',
        ),
    ]
