# Generated by Django 4.2.9 on 2024-03-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_rename_volunteers_volunteer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerrole',
            old_name='volunteers',
            new_name='volunteer',
        ),
    ]
