# Generated by Django 4.2.9 on 2024-03-17 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_rename_volunteers_volunteerrole_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrole',
            name='date_entered',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerrole',
            name='volunteer_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
