# Generated by Django 5.0.6 on 2024-05-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0011_volunteerroles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerRoles',
        ),
        migrations.RemoveField(
            model_name='volunteerrole',
            name='volunteer',
        ),
    ]
