# Generated by Django 5.0.6 on 2024-06-04 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0014_rename_volunteer_role_volunteerrole_vol_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteerrole',
        ),
        migrations.AddField(
            model_name='volunteerrole',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.volunteer'),
        ),
    ]
