# Generated by Django 5.0.6 on 2024-06-05 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0016_alter_volunteerrole_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrole',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer'),
        ),
    ]
