# Generated by Django 5.0.6 on 2024-06-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0020_alter_volunteerrole_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRolesCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_role_catalog_description', models.CharField(blank=True, max_length=200, null=True)),
                ('vol_role_catalog', models.CharField(max_length=50)),
            ],
        ),
    ]
