# Generated by Django 5.0.6 on 2024-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0021_volunteerrolescatalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrole',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteerrole',
            name='volunteer',
            field=models.ManyToManyField(default=None, null=True, to='volunteer.volunteer'),
        ),
    ]
