# Generated by Django 5.0.6 on 2024-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0022_remove_volunteerrole_volunteer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrole',
            name='volunteer',
            field=models.ManyToManyField(default=None, to='volunteer.volunteer'),
        ),
    ]
