# Generated by Django 5.0.6 on 2024-06-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0023_alter_volunteerrole_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrole',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_roles',
            field=models.ManyToManyField(to='volunteer.volunteerrole'),
        ),
    ]
