# Generated by Django 5.0.6 on 2024-06-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0024_remove_volunteerrole_volunteer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_roles',
        ),
        migrations.AddField(
            model_name='volunteerrole',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer'),
        ),
    ]
