# Generated by Django 5.0.6 on 2024-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0025_remove_volunteer_volunteer_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_roles',
            field=models.ManyToManyField(to='volunteer.volunteerrolescatalog'),
        ),
    ]
