# Generated by Django 5.0.6 on 2024-06-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0026_volunteer_volunteer_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_roles',
        ),
        migrations.RemoveField(
            model_name='volunteerrole',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.volunteerrole'),
        ),
    ]
