# Generated by Django 5.0.6 on 2024-06-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0027_remove_volunteer_volunteer_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_role',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_role',
            field=models.ManyToManyField(related_name='volunteer_role', to='volunteer.volunteerrole'),
        ),
    ]
