# Generated by Django 5.0.6 on 2024-06-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0028_remove_volunteer_volunteer_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_role',
            field=models.ManyToManyField(related_name='volunteer_role', to='volunteer.volunteerrolescatalog'),
        ),
    ]
